### ISSUE TITLE
Where does the script look for downloads on a Debian 11 system?

### ISSUE THREAD

**Issue by ovizii** [danrahn/Plexamp-Download-Copier#5]
I've copied some downloaded music from Plexamp on Android over to a Debian 11 NAS via SCP and would like to run your script on the NAS itself and since it seems there is no parameter to pass to tell it where the downloads are located I need to know where it looks for them, so I can move them there.

**Comment by danrahn** [comment]
It looks in `$HOME/.local/share/Plexamp/Offline`, and if the folder doesn't exist, it should interactively ask you to provide it:

```
python plexampDownloadCopier.py -d /path/to/save/dir
Could not find default PlexAmp download directory. Please enter the full path to the "Offline" folder:
> 
```

If for some reason it's not asking you for the path, either you have the Linux version of PlexAmp installed and don't have anything downloaded, or something else is going wrong.

**Comment by ovizii** [comment]
Thanks for clarifying, I had not tried it out, so I didn't know it was going to ask me for the path. Will try soon and comment here with the result.

**Comment by ovizii** [comment]
IT worked as you described, thanks for making this script!
